name: nom_indexer

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  znn_sdk_dart:
    git:
      url: https://github.com/zenon-network/znn_sdk_dart.git
      ref: master
  postgresql2: ^1.0.2
  settings_yaml: ^3.4.0
